package ca.bomberfish.glasstodon;

import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;
import ca.bomberfish.glasstodon.model.Account;
import main.java.ca.bomberfish.glasstodon.ScanActivity;
import android.content.Intent;
import android.app.Activity;
import android.content.Context;
import android.media.AudioManager;
import android.os.Bundle;
import android.os.AsyncTask;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import java.io.IOException;

/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 *
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class MainActivity extends Activity {

    /**
     * {@link CardScrollView} to use as the main content view.
     */
    private CardScrollView mCardScroller;

    /**
     * "Hello World!" {@link View} generated by {@link #buildView()}.
     */
    private View mView;

    private static final int REQUEST_CODE_SCAN = 1;

    AppStorage storage;

    Account account;

    private class FetchAccountTask extends AsyncTask<Void, Void, Account> {
        private IOException error;
        
        @Override
        protected Account doInBackground(Void... voids) {
            try {
                MastoAPI api = new MastoAPI(storage.getInstanceUrl(), storage.getAccessToken());
                return api.getMe();
            } catch (IOException e) {
                // Handle error (e.g. show a message to the user)
                Log.e("MainActivity", "Failed to fetch account info: " + e.getMessage());
                error = e;
                return null;
            }
        }

        @Override
        protected void onPostExecute(Account result) {
            if (result != null) {
                account = result;
                mView = buildView();
            } else {
                // Handle error (e.g. show a message to the user)
                Log.e("MainActivity", "Failed to fetch account info: " + error.getMessage());
                mView = new CardBuilder(MainActivity.this, CardBuilder.Layout.TEXT)
                        .setText("Failed to load account info.\nPlease check your network connection and try again.")
                        .getView();
            }
            mCardScroller.getAdapter().notifyDataSetChanged();
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == REQUEST_CODE_SCAN) {
            if (resultCode == RESULT_OK) {
                // Successfully got credentials from the scan activity, save them and refresh the view
                String instanceUrl = data.getStringExtra("InstanceURL");
                String accessToken = data.getStringExtra("AccessToken");
                storage.saveCredentials(instanceUrl, accessToken);
                setupView();
            } else {
                // Failed to get credentials, exit the app
                finish();
            }
        }
    }

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        storage = new AppStorage(this);

        if (!storage.isLoggedIn()) {
            // Not logged in, go to the scan activity to get credentials
            Intent intent = new Intent(this, ScanActivity.class);
            startActivityForResult(intent, REQUEST_CODE_SCAN);
        } else {
            setupView();
        }
    }

    private void setupView() {
        mView = new CardBuilder(this, CardBuilder.Layout.TEXT)
        .setText("Signing in...")
        .getView();


        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(new CardScrollAdapter() {
            @Override
            public int getCount() {
                return 1;
            }

            @Override
            public Object getItem(int position) {
                return mView;
            }

            @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                return mView;
            }

            @Override
            public int getPosition(Object item) {
                if (mView.equals(item)) {
                    return 0;
                }
                return AdapterView.INVALID_POSITION;
            }
        });
        // Handle the TAP event.
        mCardScroller.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // Plays disallowed sound to indicate that TAP actions are not supported.
                AudioManager am = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
                am.playSoundEffect(Sounds.DISALLOWED);
            }
        });
        setContentView(mCardScroller);
        mCardScroller.activate();

        // Fetch account info in the background and update the view when done
        new FetchAccountTask().execute();
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (mCardScroller != null) {
            mCardScroller.activate();
        }
    }

    @Override
    protected void onPause() {
        if (mCardScroller != null) {
            mCardScroller.deactivate();
        }
        super.onPause();
    }

    /**
     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.
     */
    private View buildView() {
        CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);

        String displayName = account.getDisplayNameOrUsername();
        String info = displayName + "\n@" + account.acct
            + "\n\n" + account.followersCount + " followers · " + account.followingCount + " following";
        card.setText(info);

        return card.getView();
    }

}
